version: "3.8"

services:
  interview-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma
      - /app/node_modules
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "sleep 5 && npx prisma generate && npx prisma migrate deploy && npm run dev"
    env_file:
      - .env
    networks:
      - interview-network
    restart: unless-stopped

  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: interview_saas
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - interview-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres-data:

networks:
  interview-network:
    name: interview-network
    driver: bridge
