import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { SidebarDemo } from "@/components/Sidebar";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative min-h-screen w-full overflow-hidden bg-black flex`}
      >
        {/* Blue gradient spot */}
        <Toaster richColors position="top-right" />
        <div
          className="absolute right-0 top-0 w-[1500px] h-[400px] rounded-full translate-x-1/4 translate-y-[-50%]"
          style={{
            background: `radial-gradient(circle, rgba(0,149,189,0.7) 0%, rgba(0,149,189,0.2) 40%, rgba(0,0,0,0) 70%)`,
            filter: "blur(100px)",
          }}
        />
        <SidebarDemo />
        <div className="flex-1">{children}</div>
      </body>
    </html>
  );
}
