import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { SidebarDemo } from "@/components/Sidebar";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Intervu - Ace your next interview",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.png", // You can also use .png or .svg
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <div
        className={`${geistSans.variable} ${geistMono.variable} font-sans antialiased relative min-h-screen w-full h-screen overflow-hidden bg-black flex`}
      >
        <Toaster richColors position="top-right" />
        <div
          className="absolute inset-0 overflow-hidden pointer-events-none"
          style={{ zIndex: 1 }}
        >
          <div
            className="absolute -right-96 -top-48 w-[1500px] h-[300px] rounded-full"
            style={{
              background: `radial-gradient(circle, rgba(0,149,189,0.6) 0%, rgba(0,149,189,0.2) 40%, rgba(0,0,0,0) 70%)`,
              filter: "blur(100px)",
              mixBlendMode: "screen",
            }}
          />
        </div>

        {/* Sidebar stays fixed */}
        <div className="h-screen">
          <SidebarDemo />
        </div>

        {/* Main content scrolls */}
        <div className="flex-1 overflow-y-auto h-screen">{children}</div>
      </div>
    </ClerkProvider>
  );
}
